FROM node:22-alpine

# Set up directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN rm -rf node_modules package-lock.json && npm install
COPY . .

# Start the Vue app
CMD ["npm", "run", "dev"]
