spring:
  application:
    name: backend
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:db2://db2instance:50000/TESTDB
    username: db2inst1
    password: my-db2-password
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
